### PR TITLE
Add proper shrinking methods for string and numeric generators

### PR DESCRIPTION
**Pull request by mfelsche**

### CODE REVIEW

**Comment by mfelsche** [comment]
this is compiling just fine, but as it is using ponyc from bintray it does not yet have https://github.com/ponylang/ponyc/pull/2212 so the tests are running infinitely.
I checked locally against pony built from source and all tests run just fine.

**Comment by Theodus** [comment]
@mfelsche I suggest restarting the Travis build to see if it still fails

**Comment by mfelsche** [comment]
@Theodus we need to wait for a new ponyc release. the travis script installs the deb package of ponyc

**Comment by Theodus** [comment]
That makes sense

**Comment by mfelsche** [comment]
@Theodus would you do me the honour and merge this? :)

**Comment by mfelsche** [comment]
Much obliged

**Pull request merged**
