### PR TITLE
make formatting more consistent

### LINKED ISSUE #2: move to new random implementation
move away from ``MT`` and use ``XorOshiro128Plus`` or ``random.Rand``.

### PR DESCRIPTION
**Pull request by Theodus**
This PR makes the formatting across the code base more consistent. My goal is not to impose any particular style on the code, so please feel free to question any changes that I have made. Also, this closes #2 with the replacement of MT with Rand ([which is just a type alias for XorOshiro128Plus](https://github.com/ponylang/ponyc/blob/65ebcc4c7f238bb2d5a81d8a162039466c2d2235/packages/random/random.pony#L19)).

### CODE REVIEW

**Comment by mfelsche** [comment]
thank you very much!
I personally don't mind how stuff is formatted as long as it is consistent and readable, so this is totally fine and much appreciated.

Did you use some formatting tool, i could include in my workflow so, i the formatting is kept consistent over time?

**Comment by mfelsche** [comment]
The only concern i have is that maybe the seed for the Rand should be two ``U64``s or one ``U128`` as this seems to give users full control over the Rand used. Or is the XorOshiro128Plus meant to be initialized with only a single long?

**Comment by Theodus** [comment]
Good point, I added a second optional seed for any user who wishes to use it. The formatting was done manually, sadly we likely won't have a tool for that until we bootstrap the compiler.

**Comment by mfelsche** [comment]
Awesome!!!

**Pull request merged**
